apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 60
  template:
    spec:
      containers:
        - name: sample-job
          image: istsh/secret-sample-app-job:1.0.0
          args: ["fail"]
      restartPolicy: Never
