apiVersion: batch/v1
kind: Job
metadata:
  name: sample-job
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "2"
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: sample-job
          image: istsh/secret-sample-app-job:1.0.1
          args: ["success"]
      restartPolicy: Never
