apiVersion: v1
kind: Service
metadata:
  name: secret-sample-proxy-active
spec:
  selector:
    app: secret-sample-proxy
  type: NodePort
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 10000
      nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: secret-sample-proxy-preview
spec:
  selector:
    app: secret-sample-proxy
  type: NodePort
  ports:
    - name: proxy
      protocol: TCP
      port: 8080
      targetPort: 10000
      nodePort: 30002
